name: Update Folder

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update Folder
        run: |
          cd "/home/runner/work/test/test"  # Caminho onde o repositório é clonado
          cd "caminho/para/sua/pasta"  # Caminho para a sua pasta, relativo ao diretório do repositório
          git pull
