name: Update Folder

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update Folder
        run: |
          cd "C:\Users\Ezequiel\OneDrive\Área de Trabalho\Nova pasta"  # Coloque o caminho para a sua pasta entre aspas
          git pull
