name: Atualizar pasta quando o repositório for atualizado

on:
  push:
    branches:
      - main  # Substitua "main" pelo nome da sua branch principal

jobs:
  update_folder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Verificar o repositório
      uses: actions/checkout@v2
      
    - name: Atualizar a pasta
      run: |
        # Crie um comando que copie ou sincronize os arquivos da pasta desejada
        cp -r test C:\Users\Ezequiel\OneDrive\Área de Trabalho\Nova pasta\test
