name: Update Folder

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update Folder
        run: |
          cd "/home/runner/work/test/test"  # Caminho onde o repositório é clonado
          cp -r "test/Aonde parei" "C:\Users\Ezequiel\OneDrive\Área de Trabalho\Nova pasta"  # Copia os arquivos da pasta1 para a pasta local
          cp -r "caminho/para/repositório/pasta2" "/caminho/para/sua/pasta"  # Copia os arquivos da pasta2 para a pasta local
